language: node_js

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher --config-file mocha.conf --test-run-id 110910 --only=tests

script:
  - mocha test --recursive --reporter mocha-junit-reporter

after_script:
   - hiptest-publisher --config-file mocha.conf --push=test-results.xml --test-run-id 110910 --push-format junit
 