language: node_js

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c mocha.conf --only=tests --test-run-id=110894

script:
  - mocha test --recursive --reporter mocha-junit-reporter

after_script:
  - hiptest-publisher -c mocha.conf --push="test-results.xml" --test-run-id=110894
